language: python
dist: xenial
python: 3.7
install: pip install panda3d>=1.10.6
script:
 - python setup.py build_apps
 - python setup-win.py build_apps
 - cd build/manylinux1_x86_64 && ./cosmonium --test-start
 - cat ~/.local/share/cosmonium/output.log
