name: build
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install panda3d>=1.10.6
    - name: Build binary
      run: |
        python setup.py bdist_apps -p manylinux1_x86_64,manylinux1_i686
    - name: Test binary
      run: |
        cd build/manylinux1_x86_64
        ./cosmonium --test-start
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: linux-logs
        path: ~/.local/share/cosmonium/output.log
    - name: 'Upload development build'
      if: github.ref == 'refs/heads/develop'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-linux"
        prerelease: true
        title: "Linux Development Build"
        files: dist/*

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install panda3d>=1.10.6
    - name: Build binary
      run: |
        python setup.py bdist_apps -p macosx_10_9_x86_64
    - name: Test binary
      run: |
        cd build/macosx_10_9_x86_64/cosmonium.app/Contents/MacOS
        ./cosmonium --test-start
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: macos-logs
        path: ~/Documents/cosmonium/output.log
    - name: 'Upload development build'
      if: github.ref == 'refs/heads/develop'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-macos"
        prerelease: true
        title: "MacOS Development Build"
        files: dist/*

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install panda3d>=1.10.6
    - name: Build binary
      run: |
        python setup.py bdist_apps -p win_amd64,win32
    - name: Test binary
      run: |
        cd build/win_amd64
        & ./cosmonium.exe --% --test-start
        cd ../win32
        & ./cosmonium.exe --% --test-start
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: windows-logs
        path: ~/AppData/Local/cosmonium/output.log
    - name: 'Upload development build'
      if: github.ref == 'refs/heads/develop'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-windows"
        prerelease: true
        title: "Windows Development Build"
        files: dist/*

