name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install panda3d>=1.10.6
    - name: Build binary (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        python setup.py bdist_apps -p manylinux1_x86_64,manylinux1_i686
    - name: Test binary (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        cd build/manylinux1_x86_64
        ./cosmonium --test-start
    - name: Upload logs (Linux)
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2
      with:
        name: linux-logs
        path: ~/.local/share/cosmonium/output.log
    - name: Build binary (macOS)
      if: runner.os == 'macOS'
      run: |
        python setup.py bdist_apps -p macosx_10_9_x86_64
    - name: Test binary (macOS)
      if: runner.os == 'macOS'
      run: |
        cd build/macosx_10_9_x86_64/cosmonium.app/Contents/MacOS
        ./cosmonium --test-start
    - name: Upload logs (macOS)
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v2
      with:
        name: macos-logs
        path: ~/Documents/cosmonium/output.log
    - name: Build binary (Windows)
      if: runner.os == 'Windows'
      run: |
        python setup.py bdist_apps -p win_amd64,win32
    - name: Test binary (Windows)
      if: runner.os == 'Windows'
      run: |
        set PYTHONUNBUFFERED=1
        cd build/win_amd64
        & ./cosmonium.exe --% --test-start
        cd ../win32
        & ./cosmonium.exe --% --test-start
    - name: Upload logs (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: windows-logs
        path: ~/AppData/Local/cosmonium/output.log
    - name: 'Upload development build (Ubuntu)'
      if: runner.os == 'Linux'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-linux"
        prerelease: true
        title: "Linux Development Build"
        files: dist/*
    - name: 'Upload development build (macOS)'
      if: runner.os == 'macOS'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-macos"
        prerelease: true
        title: "MacOS Development Build"
        files: dist/*
    - name: 'Upload development build (Windows)'
      if: runner.os == 'Windows'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-windows"
        prerelease: true
        title: "Windows Development Build"
        files: dist/*
